EMAIL_ERROR_MSG = "Email is required"
STAFF_FLAG = "is_staff"
SUPERUSER_FLAG = "is_superuser"
DONOR_GP = "donor_groups"
DONOR_PERMISSION = "donor_permissions"
MAX_LENGTH = 255
SMALL_MAX_LENGTH = 17
DECIMAL_MAX_LENGTH = 7
NGO_DESCOINS = 500
DONOR_DESCOINS = 0
HOME_FOOD = "homefood"
PARTY = "party"
RESTAURANT = "restro"
OTHER = "other"
D2N = "donor_to_ngo"
N2D = "ngo_to_donor"
D2U = "donor_to_us"
U2N = "us_to_ngo"
NGO_DONATION = "ngo_donations"
DESCOINS = "descoins"
EXP_DATE = "exp_date"
MIN = "min_quantity"
MAX = "max_quantity"
PIN = "pincode"
DISTANCE = "distance"
SUCCESS_REDEEM = "Transaction Successful."
FAIL_REDEEM = "You do not have enough DESCOINS"
DONOR_MAIL = "donor_email"
INVALID = "Invalid Request"
NULL_FEILD_ERROR = "Please enter DESCOINS to be donated"
DEFAULT_MIN = 0
DEFAULT_MAX = 10000
BASE_VAL = 5
DONATION_ERROR = "Donation not found."
ID2 = "donation_id2"
ID1 = "donation_id"
CONST_2 = 2
FORM = "form"
NGOS = "ngos"
DONOR = "donor"
DONATIONS_MADE = "donations_made"
CONST_1 = 1
