# Generated by Django 4.1.7 on 2023-02-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sent', models.DateField(auto_now_add=True)),
                ('seen', models.DateField()),
                ('sent_time', models.TimeField(auto_now_add=True)),
                ('seen_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=248001)),
                ('city', models.CharField(default='es', max_length=250)),
                ('state', models.CharField(default='qw', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngo_name', models.CharField(default='a', max_length=255)),
                ('email', models.CharField(default='b', max_length=55)),
                ('phone_no', models.IntegerField(default=123456789)),
                ('longitude', models.DecimalField(decimal_places=10, default=2.313, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, default=13.131, max_digits=15)),
                ('pincode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=55)),
                ('phone_no', models.IntegerField()),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('pincode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='donations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('exp_date', models.DateField()),
                ('quantity', models.IntegerField(default=10)),
                ('desc', models.TextField(default='xyz')),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.donor')),
                ('ngo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ngo')),
            ],
        ),
    ]
