# Generated by Django 4.1.7 on 2023-02-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sent', models.DateField(auto_now_add=True)),
                ('seen', models.DateField()),
                ('sent_time', models.TimeField(auto_now_add=True)),
                ('seen_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=55)),
                ('phone_no', models.IntegerField()),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('locality', models.TextField(default='hj')),
                ('city', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='invent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('exp_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('desc', models.TextField(default='xyz')),
            ],
        ),
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=55)),
                ('phone_no', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('locality', models.TextField(default='ghjv')),
                ('city', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates_served_week', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('plates_served_month', models.IntegerField()),
                ('plates_served_total', models.IntegerField()),
            ],
        ),
    ]
