# Generated by Django 4.1.7 on 2023-03-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=95),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(max_length=95),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngo_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ngo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_transactions', to='inventory.ngo'),
        ),
    ]
