# Generated by Django 4.1.7 on 2023-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sent', models.DateField()),
                ('seen', models.DateField()),
                ('sent_time', models.TimeField()),
                ('seen_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=55)),
                ('phone_no', models.IntegerField()),
                ('points', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('status', models.BooleanField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.TextField()),
                ('city', models.CharField(max_length=250)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=55)),
                ('phone_no', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates_served_week', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('plates_served_month', models.IntegerField()),
                ('plates_served_total', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsite',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productsite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsite',
            name='productsize',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductSite',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
