# Generated by Django 4.1.7 on 2023-03-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donations",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=17),
        ),
        migrations.AlterField(
            model_name="donations",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=17),
        ),
        migrations.AlterField(
            model_name="donor",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="donor",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=17),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=17),
        ),
        migrations.AlterField(
            model_name="pincode",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pincode",
            name="state",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("donor_to_ngo", "donor_to_ngo"),
                    ("ngo_to_donor", "ngo_to_donor"),
                    ("donor_to_us", "donor_to_us"),
                    ("us_to_ngo", "us_to_ngo"),
                ],
                max_length=17,
            ),
        ),
    ]
