# Generated by Django 4.1.7 on 2023-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction_code",
            name="type",
        ),
        migrations.AddField(
            model_name="transaction_code",
            name="receiver",
            field=models.CharField(default="receiver", max_length=255),
        ),
        migrations.AddField(
            model_name="transaction_code",
            name="sender",
            field=models.CharField(default="donor", max_length=255),
        ),
    ]
