# Generated by Django 4.1.7 on 2023-03-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=55),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(default='b', max_length=55),
        ),
    ]
