# Generated by Django 4.1.7 on 2023-03-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=15, null=True),
        ),
    ]
