# Generated by Django 4.1.7 on 2023-03-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_basetransaction_ngodonation_t_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetransaction',
            name='points_transferred',
            field=models.IntegerField(),
        ),
    ]
