# Generated by Django 4.1.7 on 2023-02-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_invent_desc_remove_invent_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invent',
            name='donor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor1', related_query_name='donor1', to='inventory.donor'),
        ),
    ]
