# Generated by Django 4.1.7 on 2023-02-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_invent_donor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invent',
            name='donor_id',
        ),
        migrations.AddField(
            model_name='invent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation', related_query_name='donation', to=settings.AUTH_USER_MODEL),
        ),
    ]
